version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    ports:
      - "5430:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=passw0rd
    networks:
      dev-network:

  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: api
    volumes:
      - ./server:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    ports:
      - "8080:8080"
    env_file:
      - server/.env_server
    depends_on:
      - postgres
    restart: always
    networks:
      dev-network:

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    platform: linux/arm64
    volumes:
      - /usr/src/app/.next
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    container_name: app
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      dev-network:

volumes:
  db-store:
  cargo-cache:
  target-cache:

networks:
  dev-network:
    driver: bridge
