env:
  browser: true
  es2021: true
plugins:
  - solid
extends:
  - standard-with-typescript
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - plugin:solid/recommended
  - plugin:jsx-a11y/strict
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
rules:
  no-unused-vars: off