\c dev

CREATE TABLE users (
    id serial PRIMARY KEY,
    display_name varchar NOT NULL,
    email varchar(256) UNIQUE NOT NULL,
    password varchar(256) NOT NULL,
    point int NOT NULL,
    is_admin bool NOT NULL
);

CREATE TABLE products (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(256) UNIQUE NOT NULL,
    price int NOT NULL,
    stock int NOT NULL
);

CREATE TABLE orders (
    id uuid PRIMARY KEY,
    user_id int,
    total int NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE order_items (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id uuid NOT NULL,
    product_id int NOT NULL,
    quantity int NOT NULL,
    UNIQUE (order_id, product_id)
);

ALTER TABLE orders ADD FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE order_items ADD FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE order_items ADD FOREIGN KEY (product_id) REFERENCES products (id);

CREATE TYPE item AS (name VARCHAR(256), price INT, quantity INT);

CREATE OR REPLACE VIEW order_view AS
    SELECT
        o.id,
        o.user_id,
        o.created_at,
        o.total,
        ARRAY_AGG(ROW(p.name, p.price, i.quantity)::item) AS items
    FROM
        orders AS o
            INNER JOIN
        order_items AS i
        ON i.order_id = o.id
            INNER JOIN
        products AS p
        ON p.id = i.product_id
    GROUP BY o.id;

INSERT INTO products (name, price, stock)
    VALUES
        ('定食A', 420, 100),
        ('定食B', 420, 100),
        ('ライスボール', 390, 100),
        ('カツ丼', 360, 100),
        ('親子丼', 360, 100),
        ('カツカレー', 360, 100),
        ('天ぷらうどん', 300, 100),
        ('天ぷらそば', 300, 100),
        ('きつねうどん', 250, 100),
        ('きつねそば', 250, 100),
        ('ミニうどん', 100, 100),
        ('肉うどん', 300, 100),
        ('肉そば', 300, 100),
        ('日替わりラーメン', 310, 100),
        ('カレーライス(大)', 310, 100),
        ('カレーライス(小)', 180, 100),
        ('味噌汁', 50, 100),
        ('カルボナーラ', 310, 100),
        ('ライス(大)', 160, 100),
        ('ライス(中)', 140, 100),
        ('ライス(小)', 90, 100);

INSERT INTO users (id, display_name, email, password, point, is_admin)
    VALUES
        (1, 'demo', 'demo', 'demo', 10000, true);
