@startuml usecase
skinparam actorStyle awesome
left to right direction

actor ゲストユーザー
actor ログインユーザー

usecase 注文内容を選択する
usecase 注文内容を確定する
usecase 注文内容を確認する
usecase 注文内容を更新する
usecase 注文内容を削除する
usecase サインインする
usecase サインアップする


ゲストユーザー --> サインインする
ゲストユーザー --> サインアップする

ログインユーザー --> 注文内容を選択する
ログインユーザー --> 注文内容を確定する
ログインユーザー --> 注文内容を確認する
ログインユーザー --> 注文内容を更新する
ログインユーザー --> 注文内容を削除する


サインアップする ..> サインインする : 発生
注文内容を選択する ..> サインインする : 先行
注文内容を確定する ..> 注文内容を選択する : 先行
注文内容を更新する ..> 注文内容を確定する : 先行
注文内容を削除する ..> 注文内容を確定する : 先行


@enduml