name: test

on:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Checkout And Build
        run: docker compose -f docker-compose.test.yaml up -d

      - name: Serverside test
        run: docker compose -f docker-compose.test.yaml exec -T api cargo test
